language: ruby
rvm:
  - 1.8.7
  - 1.9.3

# uncomment this line if your project needs to run something other than `rake`:
#before_script: # for Selenium RSpec tests
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

before_script:
script: bundle exec rspec

